<?php  require_once "./head.phtml"; 
        
?>

<div >
    <form  action="" method="post">

    <h1>Ajout d'utilisateur</h1>

    <div >

      <label for="name">NOM</label>
      <input type="text" name="name"  placeholder="Metez votre Nom">

    </div>

    <div >

      <label for="username">Nom d'utilisateur</label>
      <input type="text" name="username"  placeholder="Metez votre prenom">

    </div>

    <div >

      <label for="email">Email address</label>
      <input type="email" name="email"  placeholder="Metez votre email">

    </div>

    <div >

      <label for="mobile">telephone</label>
      <input type="text" name="mobile"  placeholder="Metez votre numero telephonique">

    </div>

    <div >

      <label for="password">Mot de passe</label>
      <input type="password" name="password" placeholder="Metez votre mot de passe">

    </div>

    <div >
      <div >

        <label for="sel1">Selectionnez le  Role</label>
        <select  name="roleid" id="roleid">
          <option disabled selected>choisissez le role</option>
          <option value="1">Admin</option>
          <option value="2">Editor</option>
          <option value="3">User only</option>

        </select>

      </div>
    </div>
   
      <button type="submit" name="addUser" >Register</button>
    </div>


</form>
</div>