
	 <!-- requiered header -->
     <?php  require_once "./head.phtml"; ?>
	<!-- end required header -->
  
    <body>
        <form action="/DashboadModels/changeRole">
            <select name="role" id="">
                <option value="user">User</option>
                <option value="admin">Admin</option>
            </select>
            <input type="submit" name="submit" value="modifier">
        </form>
    </body>
    </html>