
  <?php  require_once "./head.phtml"; ?>
  <?php  require_once "./header.phtml"; ?>



<body>
<main class="blog">

    <div class="container">
        <h1 class="page_title">Le Blog</h1>

        <article>
            <div>
                <img class="blog_picture" src="../ressources/photos/tente.jpg" alt="Cabane au milieu de rien">
                <h2>La Fête des sorcières en forêt de Masaka</h2>

                <div class="texte">
                    <p class="texte_article"> Issue de la grande forêt centrale primitive de Bretagne, la forêt de Masaca 
                        est une forêt de légendes où chaque année sorcières, sorciers, trolls, lutins et autres korrigans
                        se retrouvent pour une grande fête à laquelle toute la famille est conviée.</p>
                    <p class="texte_article"> Tout au long de la journée des spectacles et des concerts se succéderont,<br>
                    ainsi que de nombreux ateliers autour de l’écologie et de la préservation de la nature.
                    Le circuit ne présente pas de dangers et est accessible, ainsi que tous les jeux,<br> 
                    à tous les enfants dès l’âge de 3 ans. À la nuit tombée, la fête s’adressera aux adultes,
                    et la sorcellerie et les sortilèges seront à l’honneur. De nombreuses activités telles que
                    la voyance, le spiritisme et la méditation seront proposées, encadrées par des professionnels.</p>
                    <p class="texte_article"> L’origine de cette fête remonte à l’ère pré-chrétienne quand des feux de joie<br> 
                        étaient allumés et des danses païennes faisaient partie de la célébration du printemps.
                        A l’époque médiévale, les sorcières étaient chassées car on les croyait associées au diable.<br> 
                        Lors de la Nuit de Walpurgis, les sorcières s’envolaient sur leurs balais vers leurs lieux de 
                        sacrifice pour rencontrer d’autres sorcières. Des feux de joie étaient allumés 
                        et des coups de feu tirés pour effrayer les sorcières.</p>
                    <p class="texte_article"> Aujourd’hui encore, la tradition continue pour le bonheur de tous, 
                        et cette année encore nous vous attendons en forêt de Masaca pour un moment forcément féerique.</p>

                </div>
            </div>
        </article>

        <div class="signature">
            <p>Par Hélène</p>
            <p>|</p>
            <p><time datetime="2021-03-16">16/03/2021</time></p>
            <p>|</p>
            <p>Le Blog</p>
        </div>
    
    </div>

    <div class="container">

        <p>Articles similaires</p>

        <div class="articles_similaires">

            <div class="article">
                <div>
                    <a href="#"><img class="images_articles" src="../ressources/photos/lake.jpg" alt="Lac"></a>
                </div>

                <p class="description_image">
                    <a href="#">Une baignade à Masaca</a >
                </p>

                <p class="description_image"><time datetime="2020-12-02">02/12/2020</time></p>

            </div>

            <div class="article">

                <div><a href="#"><img  class="images_articles" src="../ressources/photos/promenade.jpg" alt="Femme de dos portant son backpack"></div>
                <p><a href="#">Carnet de vacances Episode 1</a></p>
                <p><time datetime="2020-06-12">12/06/2020</time></p>

            </div>

            <div class="article">

                <div><a href="#"><img class="images_articles" src="../ressources/photos/promenade2.jpg" alt="Chemin dégagé en forêt"></a></div>
                <p><a href="#">Concert en forêt de Masaka</a></p>
                <p class="description_time"><time datetime="2019-08-03">03/08/2019</time></p>
                
            </div>

        </div>
    </div>
  </main>
    <!-- requiered footer -->
    <?php  require_once  "./footer.phtml" ?>
        <!-- end required footer -->
</body>
</html>