

<!-- requiered header -->
<?php  require_once "./head.phtml";
if(!isset($_SESSION["admin"])) {

    header('Location:/register');

}
?>
<!-- end required header -->

    <body>

        <input type="checkbox" class="sidebar__toggle">
        <div class="sidebar">
        
            <div class="sidebar__header">

                <h3 class="brand">
                    <span class="ti-unlink"></span>
                    <span>SimpleDash</span>
                    
                </h3> 
                <label for="sidebar__toggle" class="ti-menu-alt"></label>
            
            </div>

            <div class="sidebar__menu">
                
                <ul>
                    <li>
                        <a href="#article">
                            <span class="ti-home"></span>
                            <span>Home</span>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <span class="ti-face-smile"></span>
                            <span>Article</span>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <span class="ti-agenda"></span>
                            <span>Message page contact</span>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <span class="ti-clipboard"></span>
                            <span>article</span>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <span class="ti-folder"></span>
                            <span>Ajouter un image</span>
                        </a>
                    </li>
                    
                    <li>
                        <a href="">
                            <span class="ti-book"></span>
                            <span>Contacts</span>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <span class="ti-settings"></span>
                            <span>Account</span>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <span></span>
                            <span></span>
                        </a>
                    </li>
                    
                </ul>

            </div>
        
        </div>


        <div class="main__content">
        
            <header>
                <div class="search__wrapper">
                    <span class="ti-search"></span>
                    <input type="search" placeholder="Search..." autocomplete="off">
                </div>

                <div class="social__icons">
                    <span class="ti-bell"></span>
                    <span class="ti-comment"></span>
                    <div></div>
                </div>
            </header>

            <!--************* Dashbord admin************* -->
            <main>

                <h2 class="dashboard__title">Overview</h2>
                <div class="dashboard__cards">

                    <div class="card__single">
                        <div class="card__body">
                            
                            <span class="ti-reload"></span>
                            <!-- nombres de personne inscrit -->
                            <div>

                                <h5>Nombre de personnne inscrits</h5>
                                
                                <h4> <?= $userCount[0]["countUser"] ; ?></h4>
                            </div>
                        </div>

                        <div class="card__footer">
                            <a href="">View all</a>
                        </div>

                    </div>

                    <div class="card__single">
                        <div class="card__body">
                            <span class="ti-check-box"></span>
                            <div>
                                <h5>Nombre de reservation</h5>
                                <h4>MKW75,687.06</h4>
                            </div>
                        </div>

                        <div class="card__footer">
                            <a href="">View all</a>
                        </div>
                        
                    </div>
                    <div class="card__single">
                        <div class="card__body">
                            <span class="ti-check-box"></span>
                            <div>
                                <h5>Nombre de message des contact</h5>
                                <h4>MKW75,687.06</h4>
                            </div>
                        </div>

                        <div class="card__footer">
                            <a href="">View all</a>
                        </div>
                        
                    </div>

                </div>

                <section class="recent">

                    <div class="activity__grid">
                        <div class="activity__card">
                            <h3>Recent activity</h3>

                            <div class="table__responsive">
                                <table>
                                <thead>
                                    <tr>
                                        <th>NON du touriste: </th>
                                        <th>Prénom: </th>
                                        <th>Nom d'utilisateur: </th>
                                        <th>Email: </th>
                                        <th>telephone: </th>
                                        <th> Role </th>
                                        <th>change Role </th>
                                        
                                    </tr>
                                </thead>
                                <!-- la liste de tous les utilisateur -->
                                <tbody>
                                    <?php
                                    if(count($user) > 0){
                                        foreach ($user as $key => $value) {
                                    ?>
                                        <tr>
                                            <td><?= $user[$key]["users_fname"]; ?></td>
                                            <td><?= $user[$key]["users_lname"]; ?></td>
                                            <td><?= $user[$key]["users_username"]; ?></td>
                                            <td><?= $user[$key]["users_email"]; ?></td>
                                            <td><?= $user[$key]["users_contactNumber"]; ?></td>
                                            <td><?= $user[$key]["user_role"]; ?></td>
                                            <td> <a href="/role">Modifier</a> </td>
                                            <td> Suprimer </td>
                                        </tr>
                                    <?php
                                        }
                                        }else{
                                            echo '<p class="empty">no article added yet!</p>';
                                        }
                                        ?>
                                

                                </tbody>
                            </table>
                            </div>

                        </div>

                        <div class="summary">
                            <div class="summary__card">
                                <div class="summary__single">
                                    <span class="ti-id-badge"></span>
                                    <div>
                                        <h5>278</h5>
                                        <small>INSCRIT</small>
                                    </div>
                                </div>

                                <div class="summary__single">
                                    <span class="ti-calendar"></span>
                                    <div>
                                        <h5>18</h5>
                                        <small>Nombres de colaborateurs</small>
                                    </div>
                                </div>

                                <div class="summary__single">
                                    <span class="ti-face-smile"></span>
                                    <div>
                                        <h5>56</h5>
                                        <small>Profile complet</small>
                                    </div>
                                </div>
                            </div>

                            <div class="bday__card">
                                <div class="bday__flex">
                                    <div class="bday__img"></div>
                                    <div class="bday__info">
                                        <h5>ADIHOU tobi Rodrigues</h5>
                                        <small>ADMIN</small>
                                    </div>
                                </div>

                                <div class="text__center">
                                    <button> 
                                    <span class="ti-gift"></span>
                                        voir plus
                                    </button>
                                </div>
                            </div>
                        </div>

                    </div>

                </section>

            </main>
        
        </div>

        <script src="" ></script>
    </body>
</html>