

<!-- requiered header -->
<?php  require_once "./head.phtml";

?>
<!-- end required header -->

    <body>
                <section class="recent">

                    <div class="activity__grid">
                        <div class="activity__card">
                        <h2>Il y a <?php echo $nbrUser ?> <span class="title-nbr">utilisateurs</span> au total inscrits sur le site</h2> 

                            <div class="table__responsive">
                                <table>
                                <thead>
                                    <tr>
                                        <th>NON du touriste: </th>
                                        <th>Prénom: </th>
                                        <th>Nom d'utilisateur: </th>
                                        <th>Email: </th>
                                        <th>telephone: </th>
                                        <th> Role </th>
                                        <th>change Role </th>
                                        
                                    </tr>
                                </thead>
                                <!-- la liste de tous les utilisateur -->
                                <tbody>
                                    <?php
                                    if(count($user) > 0){
                                        foreach ($user as $key => $value) {
                                    ?>
                                        <tr>
                                            <td><?= $user[$key]["users_fname"]; ?></td>
                                            <td><?= $user[$key]["users_lname"]; ?></td>
                                            <td><?= $user[$key]["users_username"]; ?></td>
                                            <td><?= $user[$key]["users_email"]; ?></td>
                                            <td><?= $user[$key]["users_contactNumber"]; ?></td>
                                            <td><?= $user[$key]["user_role"]; ?></td>
                                            <td>
                                                <a href="/Users/edit?idUser=<?php echo $user['id']; ?>"><span>Modifier</span></a>
                                            </td>
                                            <!-- Pour chaque entrée je realise des actions de suppression -->
                                            <td>
                                                <a href="/RegisterController/deleteUser?id=<?php echo $user['id'] ;?>">
                                                    <span class="">Supprimer</span>
                                                </a>
                                            </td>
                                        </tr>
                                    <?php
                                        }
                                        }else{
                                            echo '<p class="empty">no article added yet!</p>';
                                        }
                                        ?>
                                

                                </tbody>
                            </table>
                            <a class="title right-title" href="/"><span class="glyphicon glyphicon-plus"></span>Aller sur le site</a>
                            </div>

                        </div>

                </section>

            </main>
        
        </div>

        <script src="" ></script>
    </body>
</html>