

<!-- requiered header -->
<?php  require_once "./head.phtml";

?>
<!-- end required header -->

    <body>

       
                <section class="recent">

                    <div class="activity__grid">
                        <div class="activity__card">
                            <h3>Recent activity</h3>

                            <div class="table__responsive">
                                <table>
                                <thead>
                                    <tr>
                                        <th>NON du touriste: </th>
                                        <th>Prénom: </th>
                                        <th>Nom d'utilisateur: </th>
                                        <th>Email: </th>
                                        <th>telephone: </th>
                                        <th> Role </th>
                                        <th>change Role </th>
                                        
                                    </tr>
                                </thead>
                                <!-- la liste de tous les utilisateur -->
                                <tbody>
                                    <?php
                                    if(count($user) > 0){
                                        foreach ($user as $key => $value) {
                                    ?>
                                        <tr>
                                            <td><?= $user[$key]["users_fname"]; ?></td>
                                            <td><?= $user[$key]["users_lname"]; ?></td>
                                            <td><?= $user[$key]["users_username"]; ?></td>
                                            <td><?= $user[$key]["users_email"]; ?></td>
                                            <td><?= $user[$key]["users_contactNumber"]; ?></td>
                                            <td><?= $user[$key]["user_role"]; ?></td>
                                            <td> <a href="/role">Modifier</a> </td>
                                            <td> Suprimer </td>
                                        </tr>
                                    <?php
                                        }
                                        }else{
                                            echo '<p class="empty">no article added yet!</p>';
                                        }
                                        ?>
                                

                                </tbody>
                            </table>
                            </div>

                        </div>

                        <div class="summary">
                            <div class="summary__card">
                                <div class="summary__single">
                                    <span class="ti-id-badge"></span>
                                    <div>
                                        <h5>278</h5>
                                        <small>INSCRIT</small>
                                    </div>
                                </div>

                                <div class="summary__single">
                                    <span class="ti-calendar"></span>
                                    <div>
                                        <h5>18</h5>
                                        <small>Nombres de colaborateurs</small>
                                    </div>
                                </div>

                                <div class="summary__single">
                                    <span class="ti-face-smile"></span>
                                    <div>
                                        <h5>56</h5>
                                        <small>Profile complet</small>
                                    </div>
                                </div>
                            </div>

                            <div class="bday__card">
                                <div class="bday__flex">
                                    <div class="bday__img"></div>
                                    <div class="bday__info">
                                        <h5>ADIHOU tobi Rodrigues</h5>
                                        <small>ADMIN</small>
                                    </div>
                                </div>

                                <div class="text__center">
                                    <button> 
                                    <span class="ti-gift"></span>
                                        voir plus
                                    </button>
                                </div>
                            </div>
                        </div>

                    </div>

                </section>

            </main>
        
        </div>

        <script src="" ></script>
    </body>
</html>