<?php

?>

  <?php  require_once "./head.phtml"; ?>
  <?php  require_once "./header.phtml"; ?>

        
    <main class="pageActivite">
    <div class="container">
          <h1 style="text-align:center">Nos activités</h1>
          <p style="text-align:center">Nous vous proposons de multiples activités inoubliables
            <br>N'hésitez de nous contacter pour demander un devis!<br>
            Les gites de la forêt de Masaka, pour des vacances de rêve...</p>
			<section>

				<ul class="lb-album">

					<li>
						<a href="#image-1">
							<img src="../ressources/photos/mariage-thumbs.jpg" alt="mariage">
							<span>Cérémonies</span>
						</a>

						<div class="lb-overlay" id="image-1">
							<img src="../ressources/photos/mariage-full.jpg" alt="mariage" />
							<div>
								<h3>Des évenements uniques</h3>
								<p>En forêt de Masaca, les cérémonies sont forcément féeriques</p>
							</div>
							<a href="#page" class="lb-close"> x </a>
						</div>
					</li>

					<li>
						<a href="#image-2">
							<img src="../ressources/photos/meditation-thumbs.jpg" alt="meditation">
							<span>Méditation</span>
						</a>
						<div class="lb-overlay" id="image-2">
							<img src="../ressources/photos/meditation-full.jpg" alt="meditation" />
							<div>
								<h3>Elever votre esprit</h3>
								<p>Se recentrer sur soi-même en harmonie avec la nature</p>
							</div>
							<a href="#page" class="lb-close"> x </a>
						</div>
					</li>

					<li>
						<a href="#image-3">
							<img src="../ressources/photos/thumbs.jpg" alt="Campement">
							<span>Aventure</span>
						</a>
						<div class="lb-overlay" id="image-3">
							<img src="../ressources/photos/full-3.jpg" alt="tente" />
							<div>
								<h3>Camping</h3>
								<p>Camping et Randonnée pour un parfait retour aux sources</p>
							</div>
							<a href="#page" class="lb-close"> x </a>
						</div>
					</li>

					<li>
						<a href="#image-4">
							<img src="../ressources/photos/thumbs-4.jpg" alt="image04">
							<span>Sport</span>
						</a>
						<div class="lb-overlay" id="image-4">
							<img src="../ressources/photos/escalade-full.jpg" alt="image04" />
							<div>
								<h3>Escalade</h3>
								<p>Laissez-vous tenter par des activités sportives dans un cadre spectaculaire</p>
							</div>
							<a href="#page" class="lb-close"> x </a>
						</div>
					</li>

				</ul>

			</section>
        </div>
    </main>

        <!-- requiered footer -->
            <?php require_once  "footer.phtml" ?>
        <!-- end required footer -->


</body>
</html>