<?php  require_once "./head.phtml";?>
<?php  require_once "./header.phtml";?>

<body>
   <main class="container">
     <div class="forms-container">
        <ul>
                <div class="input-field">
                    <li>
                        Photos de profil: <img src="" alt="#">
                    </li>
                </div>
                <div class="input-field">
                    <li>
                       NOM:<?= $_SESSION["fname"] ?> 
                </div>
                <div class="input-field">
                    <li>
                        Prénom:<?= $_SESSION["lname"] ?> 
                    </li>
                </div>

                <div class="input-field">
                    <li>
                        Nom d'utilisateur: <?= $_SESSION["name"] ?>
                    <li>
                </div>

                <div class="input-field">
                    <li>
                        Email: <?= $_SESSION["email"] ?>
                    </li>
                </div>

                <div class="input-field">
                    <li>
                        tel:  <?= $_SESSION["phone"] ?>
                    </li>
                </div>

                <div class="input-field">
                    <li>
                        reservation pour le :  <span></span>      au : <span></span>
                    </li>
                </div>
        </ul>
      </div>
      <form class="" action="" method="POST">
              <div >
                <label for="name">Your name</label>
                <input type="text" name="name"  >
              </div>
              <div >
                <label for="username">Your username</label>
                <input type="text" name="username"  >
              </div>
              <div >
                <label for="email">Email address</label>
                <input type="email" id="email" name="email"  >
              </div>
              <div >
                <label for="mobile">Mobile Number</label>
                <input type="text" id="mobile" name="mobile" >
              </div>


              <div class="form-group">
           
                <div >
                  <label for="sel1">Select user Role</label>
                  <select  name="roleid" id="roleid">
  

                  <option value="1" selected='selected'>Admin</option>
                  <option value="2">Editor</option>
                  <option value="3">User only</option>
                  <option value="1">Admin</option>
                  <option value="2" selected='selected'>Editor</option>
                  <option value="3">User only</option>
                  <option value="1">Admin</option>
                  <option value="2">Editor</option>
                  <option value="3" selected='selected'>User only</option>



                  </select>
                </div>
              </div>

            <input type="hidden" name="roleid" value="">
  

            

              <div >
                <button type="submit" name="update" class="btn btn-success">Update</button>
                <a  href="changepass.php?id=">Password change</a>
              </div>
         


              <div >
                <button type="submit" name="update" class="btn btn-success">Update</button>
                <a  href="changepass.php?id=">Password change</a>
              </div>
          


              <div >
                <button type="submit" name="update" class="btn btn-success">Update</button>

              </div>

      
                  <div >

                    <a  href="index.php">Ok</a>
                  </div>
       


          </form>
        </div>

    </main>
   
</body>
</html>