<footer>
      <div>
            <img src="icones/facebook_logo.svg" alt="logo Facebook">
            <ul>
                  <li>Lorem ipsum dolor sit amet.</li>
                  <li>Obcaecati inventore aperiam tempora laboriosam!</li>
                  <li>Ab harum eveniet corporis unde?</li>
                  <li>Veritatis recusandae neque a cupiditate.</li>
                  <li>Illum voluptatem ea quia corrupti.</li>
            </ul>
      </div>
      <div>
            <img src="icones/tripadvisor_logo.svg" alt="logo TripAdvisor">
            <ul>
                  <li>Lorem ipsum dolor sit amet.</li>
                  <li>Obcaecati inventore aperiam tempora laboriosam!</li>
                  <li>Ab harum eveniet corporis unde?</li>
                  <li>Veritatis recusandae neque a cupiditate.</li>
                  <li>Illum voluptatem ea quia corrupti.</li>
            </ul>
      </div>
      <div>
            <img src="icones/instagram_logo.svg" alt="logo Instagram">
            <ul>
                  <li>Lorem ipsum dolor sit amet.</li>
                  <li>Obcaecati inventore aperiam tempora laboriosam!</li>
                  <li>Ab harum eveniet corporis unde?</li>
                  <li>Veritatis recusandae neque a cupiditate.</li>
                  <li>Illum voluptatem ea quia corrupti.</li>
            </ul>
      </div>
</footer>