  <header>
       
       <!-- Header lorsque la taille de la fenêtre est supérieur à 768px-->  
         <div class="header2">
            <div class="container_logo">
                <div class="logo">
                    <img src="../ressources/photos/logo.png" alt="Logo du gîte">
                </div>
                <div class="titre">
                    <h1>Gîtes de la forêt</h1>
                    <h2>Forêt de Masaka</h2>
                </div>
            </div>
            <nav class="menu_cache ">
                <ul>
                    <li class="first_item"><a href="/" title="Vers la page d'accueil du site 'La belle Tunisie'">Accueil</a></li>
                    <li ><a href="/gites">NOS GÎTES</a></li>
                    <li><a href="/reservation">RESERVATION</a></li>
                    <li><a href="/contact">CONTACT</a></li>
                    <li><a href="/activites">A VOIR/A FAIRE</a></li>
                    <li><a href="/blog">BLOG</a></li>
                    <?php if (isset($_SESSION["user"])) : ?>
                        <li><a href="/profil">profil</a></li>
                        <li><a href="/deconnexion">deconnexion</a></li>
                    <?php else : ?>
                        <li><a href="/register">S'inscrire</a></li>
                        <li><a href="/singIn">connexion</a></li>
                    <?php endif; ?>
         
                </ul>
            </nav>
            
        </div>
    </header>  