<?php  require_once "./head.phtml"; ?>
<?php  require_once "./header.phtml"; ?>




<body>
    <!-- contact forms -->
    <main class="contact">

      <h1>CONTACT</h1>

      <form id="contact_details">

          <input type="text" placeholder="Prénom Nom">
          <input type="email" placeholder="votre@adresse">
          <textarea rows="10" placeholder="Votre message."></textarea>
          <button type="button" form="contact_details">Envoyer</button>

      </form>

   </main>
     <!-- requiered footer -->
     <?php  require_once  "./footer.phtml" ?>
        <!-- end required footer -->
    </body>
</html>