<?php
 use  App\Controllers\ContentControllers;
?>

  <?php  require_once "./head.phtml"; ?>
  <?php  require_once "./header.phtml"; ?>

<body class="bodyGite"> 

    <main class=''>

        <section class="banner">
          <div class="banner-pic">
             
              <figcaption class="presentation">
                  <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Officia sequi
                    voluptatem fuga consequuntur totam iste repellendus similique aliquid,
                    quas quos cupiditate architecto cum neque ex in illo consectetur animi!
                    ipsum dolor sit, amet consectetur adipisicing elit. Officia sequi
                    voluptatem fuga consequuntur totam iste repellendus similique aliquid,
                    quas quos cupiditate architecto cum neque ipsum dolor sit, amet consectetur
                    adipisicing elit. </p>
                  </figcaption>
               
          </div>
      </section>

      <h1>Le charme au Naturel</h1>
      
      <section class="content">
        <article class="card">
          <!-- <h1>Nos coup de coeur</h1>  -->

          <img src="../ressources/photos/cabane1.jpg" class="card-image" alt="">
          <div class="description">
            <h2>La cabane dans l'arbre</h2>
            <hr style="width:75%">
            <p>orem ipsum dolor sit, amet consectetur adipisicing elit. Officia sequi
              voluptatem fuga consequuntur totam iste repellendus similique aliquid,
              quas quos cupiditate architecto cum neque ex in illo consectetur animi!
            </p>
          </div>

        </article>

        <article class="card">

          <img src="../ressources/photos/maison2.jpg" class="card-image" alt="">

          <div class="description">
            <h2>Le chalêt de Boucle d'Or</h2>
            <hr style="width:75%">
            <p>
              orem ipsum dolor sit, amet consectetur adipisicing elit. Officia sequi
              voluptatem fuga consequuntur totam iste repellendus similique aliquid,
              quas quos cupiditate architecto cum neque ex in illo consectetur animi!
            </p>
          </div>

        </article>

      </section>

      <section class="content">
        <!-- <h2>Nos coup de coeur</h2>  -->
        <article class="card">
          <img src="../ressources/photos/maison3.jpg" class="card-image" alt="">
          <div class="description">
            <h2>La tente aménagée</h2>
            <hr style="width:75%">
            <p>orem ipsum dolor sit, amet consectetur adipisicing elit. Officia sequi
              voluptatem fuga consequuntur totam iste repellendus similique aliquid,
              quas quos cupiditate architecto cum neque ex in illo consectetur animi!
            </p>
          </div>
        </article>

        <article class="card">

          <img src="../ressources/photos/tente.jpg" class="card-image" alt="">
          <div class="description">
            <h2>La nature à l'état brut</h2>
            <hr style="width:75%">
            <p>orem ipsum dolor sit, amet consectetur adipisicing elit. Officia sequi
              voluptatem fuga consequuntur totam iste repellendus similique aliquid,
              quas quos cupiditate architecto cum neque ex in illo consectetur animi!
            </p>
          </div>

        </article>

      </section>   
  </main>
          
    <!-- requiered footer -->
    <?php  require_once  "footer.phtml" ?>
    <!-- end required footer -->
</body>
</html>