<!-- 
<//?php
 use  App\Controllers\ContentControllers;
?> -->

  <?php  require_once "./head.phtml"; ?>
 
  <?php  require_once "./header.phtml"; ?>
 <body >
            
  <main>
        <div class="image"></div>

        <section class="slideshow-container">

            <div class="mySlides fade">
                <img src="../ressources/photos/meditation2.jpg" alt="meditation2" style="width:100%; max-height:500px">
                <div class="text">Plus près de la nature</div>
            </div>

            <div class="mySlides fade">
                <img src="../ressources/photos/nature.jpg" alt="nature" style="width:100%; max-height:500px">
                <div class="text">Au coeur de la forêt</div>
            </div>

            <div class="mySlides fade">
                <img src="../ressources/photos/promenade2.jpg" alt="promenade" style="width:100%; max-height:500px">
                <div class="text">Vivez une expérience exceptionnelle</div>
            </div>

        </section>
            <article>
                <p class="article">
                    Dans la merveilleuse forêt de Masaka, venez découvrir nos gites pour<br>
                    une expérience en parfaite communion avec la nature. Que ce soit dans une maison,<br>
                    une cabane dans les arbres ou une tente, chaque séjour est unique et inoubliable.<br>
                    Venez vivre l’expérience d’un réveil paisible au milieu des arbres <br>
                    et vivez des vacances entre sport et détente pour un parfait retour aux sources.
                </p>
    
           </article>
    </main>
        <!-- requiered footer -->
        <?php  require_once  "./footer.phtml" ?>
        <!-- end required footer -->

    <script src="/ressources/js/app.js"></script>
</body>
